services:
  koordtool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:  # needed due to read-only file system
      - nginx-pid:/var/run
      - nginx-cache:/var/cache/nginx
    read_only: true
    restart: unless-stopped

volumes:
  nginx-pid:
  nginx-cache:
