services:
  limesurvey:
    image: martialblog/limesurvey:latest
    restart: always
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=example
      - DB_NAME=limesurvey
      - DB_USERNAME=limesurvey
      - ADMIN_USER=admin
      - ADMIN_NAME=Admin
      - ADMIN_PASSWORD=example
      - ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL=localhost:8082
    volumes:
      - limesurvey:/var/www/html/upload/surveys
    ports:
      - 8082:8080
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=limesurvey
      - POSTGRES_DB=limesurvey
      - POSTGRES_PASSWORD=example

volumes:
  limesurvey:
  db-data:
