export interface SurveyProperties {
    sid: number;
    owner_id: number;
    gsid: number;
    admin: string;
    active: string;
    anonymized: string;
    datestamp: string;
    additional_languages: string;
    adminemail: string;
    alloweditaftercompletion: string;
    allowprev: string;
    allowregister: string;
    allowsave: string;
    assessments: string;
    attributedescriptions: string;
    autonumber_start: number;
    autoredirect: string;
    bounce_email: string;
    bounceaccountencryption: string | null;
    bounceaccounthost: string | null;
    bounceaccountpass: string | null;
    bounceaccounttype: string | null;
    bounceaccountuser: string | null;
    bounceprocessing: string;
    bouncetime: string | null;
    emailnotificationto: string;
    emailresponseto: string;
    expires: string | null;
    format: string;
    googleanalyticsapikey: string;
    googleanalyticsstyle: string;
    htmlemail: string;
    ipaddr: string;
    ipanonymize: string;
    language: string;
    listpublic: string;
    navigationdelay: number;
    nokeyboard: string;
    printanswers: string;
    publicgraphs: string;
    publicstatistics: string;
    questionindex: number;
    refurl: string;
    savetimings: string;
    sendconfirmation: string;
    showgroupinfo: string;
    showprogress: string;
    showqnumcode: string;
    showwelcome: string;
    template: string;
    usecaptcha: string;
    usecookie: string;
  }